import React, { useState } from 'react';
import { useDispatch } from 'react-redux';
import { useNavigate } from 'react-router-dom';
import { createBoardOnServer } from '../Store/boardSlice';

function WelcomePage() {
  const [boardTitle, setBoardTitle] = useState('');
  const [loading, setLoading] = useState(false);
  const dispatch = useDispatch();
  const navigate = useNavigate();

  const handleCreateBoard = async (e) => {
    e.preventDefault();
    if (!boardTitle.trim()) return;

    setLoading(true);
    try {
      // 1. Send the dispatch action to create the board on the server
      const resultAction = await dispatch(createBoardOnServer(boardTitle.trim())).unwrap();
      // 2. Automatically navigate to the new dynamic ID generated by the server!
      navigate(`/boards/${resultAction.id}`);
    } catch (err) {
      alert("Could not connect to database to create board.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#1a1b23] text-white flex flex-col items-center justify-center p-6">
      <div className="max-w-md w-full bg-[#242630] p-8 rounded-2xl shadow-xl border border-gray-800">
        <h1 className="text-4xl font-extrabold text-center mb-2 tracking-tight bg-gradient-to-r from-blue-400 to-emerald-400 bg-clip-text text-transparent">
          TaskBoard
        </h1>
        <p className="text-gray-400 text-center mb-8 text-sm">
          Create a dynamic, persistent workspace instantly.
        </p>

        <form onSubmit={handleCreateBoard} className="flex flex-col gap-4">
          <div>
            <label className="block text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">
              Workspace Title
            </label>
            <input
              type="text"
              required
              placeholder="e.g. My Sprint Planning"
              value={boardTitle}
              onChange={(e) => setBoardTitle(e.target.value)}
              className="w-full bg-[#1a1b23] border border-gray-700 rounded-xl px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-blue-500 transition"
              disabled={loading}
            />
          </div>

          <button
            type="submit"
            className="w-full bg-blue-600 hover:bg-blue-500 py-3 rounded-xl font-bold tracking-wide shadow-lg shadow-blue-600/20 active:scale-[0.98] transition disabled:opacity-50"
            disabled={loading}
          >
            {loading ? "Initializing..." : "Create Board →"}
          </button>
        </form>
      </div>
    </div>
  );
}

export default WelcomePage;